runtime: aspnetcore
env: flex

runtime_config:
  operating_system: ubuntu22

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  # Je omgevingsvariabelen hier

handlers:
  - url: /ClassLibraryEndpoint
    script: auto
    secure: always
    # Specificeer de URL en bijbehorende script

  - url: /ApiEndpoint
    script: auto
    secure: always
    # Specificeer de URL en bijbehorende script voor de API
